// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzAP5whVVoUezYYudqUr-Ww7I6CyTcf-k',
    appId: '1:412041070568:web:5ea589bca440790215c65d',
    messagingSenderId: '412041070568',
    projectId: 'access-control-76843',
    authDomain: 'access-control-76843.firebaseapp.com',
    storageBucket: 'access-control-76843.appspot.com',
    measurementId: 'G-BKQXP4HGK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGB0KkEUqdjeIdLTf5H7Lv_r1vL56lisU',
    appId: '1:412041070568:android:c168298ea571fe3e15c65d',
    messagingSenderId: '412041070568',
    projectId: 'access-control-76843',
    storageBucket: 'access-control-76843.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBt_yFfS_TiEr87gUKJxp1LUzW6GcW064',
    appId: '1:412041070568:ios:10a4191f1e862f8a15c65d',
    messagingSenderId: '412041070568',
    projectId: 'access-control-76843',
    storageBucket: 'access-control-76843.appspot.com',
    androidClientId: '412041070568-s8f873iqubveas6772pdit7tl5brv7fi.apps.googleusercontent.com',
    iosClientId: '412041070568-2bd1ar08hnb1cglf6f4dvpbd9g01vbo8.apps.googleusercontent.com',
    iosBundleId: 'com.example.accessControlFlutter',
  );
}
